apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: springboot-mysql-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: springboot-mysql
    spec:
      containers:
      - name: springboot-mysql
        image: cnreunfast001.azurecr.io/myapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-mysql-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: springboot-mysql
